yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views
app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название сообщества', max_length=200)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL')
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True, db_index=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self) -> str:
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

        widgets = {
            "text": forms.Textarea(attrs={
                'class': 'form-control',
                'cols': '40',
                'rows': '10'
            }),
            "group": forms.Select(attrs={
                'class': 'form-control'
            })
        }

        labels = {
            'text': ('Текст поста'),
            'group': ('Группа поста')
        }

        help_texts = {
            'text': ('Введите текст поста'),
            'group': ('Выберите группу поста (опционально)')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            "text": forms.Textarea(attrs={
                'class': 'form-control',
                'rows': "3"
            })
        }
        help_texts = {
            'text': ('Введите текст поста'),
        }

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import Post, Group, Comment, Follow, User
from .forms import CommentForm, PostForm

NUMBERS_OF_POST = 10


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, NUMBERS_OF_POST)
    title = 'Последние обновления на сайте'
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all().order_by('-pub_date')
    paginator = Paginator(post_list, NUMBERS_OF_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author).order_by('-pub_date')
    paginator = Paginator(post_list, NUMBERS_OF_POST)
    post_count = post_list.filter(author_id=author).count()
    title = f'Профайл пользователя {author}'
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(author=author, user=request.user).exists():
            following = True
    context = {
        'title': title,
        'page_obj': page_obj,
        'author': author,
        'post_count': post_count,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post).order_by('-created')
    form = CommentForm(request.POST or None)
    author = post.author
    post_count = Post.objects.filter(author=author).count()
    context = {
        'post': post,
        'author': author,
        'post_count': post_count,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,

    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user
    ).order_by('-pub_date')
    paginator = Paginator(post_list, NUMBERS_OF_POST)
    title = 'Ваши подписки'
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}  
{% block title %} {% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %} {% endblock %}
{% block content %} 
  {% load user_filters %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data"
              {% if action_url %}
              action="{% url action_url%}"
              {% endif %}>
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  Текст поста
                  <span class="required text-danger" >*</span>
                </label>
                {{ form.text }}
                <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_image">
                  Картинка
                </label>
                {{ form.image }}
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_group">
                  Сообщество
                </label>
                {{ form.group }}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}

{% block title %} {{ title }} {% endblock %}

{% block content%}
  <h1>Ваши подписки</h1>
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "350x350" crop="center" upscale=True as im %}
      <img class="rounded mx-auto d-block" alt="" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <ul class="nav nav-pills">
      {% if post.group %}
        <li class="nav-item"> 
          <a class="nav-link" href="{% url 'posts:group_posts' post.group.slug %}">
            <button type="submit" class="btn btn-light"> все записи группы </button>
          </a>
        </li>
      {% endif %}
        <li class="nav-item"> 
          <a class="nav-link" href={% url 'posts:post_detail' post.id %}>
            <button type="submit" class="btn btn-light"> подробная информация </button>
          </a>
        </li>
      </ul>
    {% if not forloop.last %}<hr>{% endif %}
    </article>
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% load thumbnail%}

{% block title %} {{ group.title }} {% endblock %}
{% block content%}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "350x350" crop="center" upscale=True as im %}
        <img class="rounded mx-auto d-block" alt="" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p> 
      <p><a class="nav-link" href={% url 'posts:post_detail' post.id %}>
        <button type="submit" class="btn btn-light"> подробная информация </button>
      </a></p>
      {% if not forloop.last %}<hr>{% endif %}
    </article>
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load cache %}

{% block title %} {{ title }} {% endblock %}

{% block content%}
  <h1>Последние обновления на сайте</h1>
  {% cache 20 index_page page_obj.number %}
  {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "350x350" crop="center" upscale=True as im %}
      <img class="rounded mx-auto d-block" alt="" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <ul class="nav nav-pills">
    {% if post.group %}
      <li class="nav-item"> 
        <a class="nav-link" href="{% url 'posts:group_posts' post.group.slug %}">
          <button type="submit" class="btn btn-light"> все записи группы </button>
        </a>
      </li>
    {% endif %}
      <li class="nav-item"> 
        <a class="nav-link" href={% url 'posts:post_detail' post.id %}>
          <button type="submit" class="btn btn-light"> подробная информация </button>
        </a>
      </li>
    </ul>
    {% if not forloop.last %}<hr>{% endif %}
    </article>
    {% endfor %}
    {% endcache %}

    {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block title %}Пост {{post.text|truncatechars:30}}{% endblock %}

{% block content %}
<div class="row">
<aside class="col-12 col-md-3">
  <ul class="list-group list-group-flush">
    <ul>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group%}
        <li class="list-group-item">
          Группа: {{post.group.title}}
          <a class="nav-link" href="{% url 'posts:group_posts' post.group.slug %}">
            <button type="submit" class="btn btn-light"> все записи группы </button>
          </a>
        </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span >{{post_count}}</span>
      </li>
      <li class="list-group-item">
        <a class="nav-link" href={% url 'posts:profile' post.author %}>
          <button type="submit" class="btn btn-light"> все посты пользователя </button>
        </a>
      </li>
    </ul>
  </ul>
</aside>
<article class="col-12 col-md-9">
<div class="card">
  <div class="card-body">
  {% thumbnail post.image "350x350" crop="center" upscale=True as im %}
    <img class="rounded mx-auto d-block" alt="" src="{{ im.url }}">
  {% endthumbnail %}
    <p>{{ post.text }}</p> 
  <a class="nav-link" href={% url 'posts:post_edit' post.id %}>
    <button type="submit" class="btn btn-primary"> Редактировать </button>
  </a>
</div>
</div>
</article>
</div>
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

<div class="card my-4">
  <h5 class="card-header">Комментрии</h5>
    <div class="card-body">
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a class="nav-link" href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.get_full_name }}
              </a>
            </h5>
            {{ comment.text }}
          </div>
        </div>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% load thumbnail%}

{% block title %} {{ title }} {% endblock %}

{% block content%}
<div class="mb-5">
  <h1>Все посты пользователя {{author.get_full_name}} </h1>
  <h3>Всего постов: {{post_count}} </h3>
  {% if user != author %}
  {% if following %}
    <a
      class="btn btn-lg btn-light" id="unfollow"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
   {% endif %}
</div>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "350x350" crop="center" upscale=True as im %}
        <img class="rounded mx-auto d-block" alt="" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <ul class="nav nav-pills">
        {% if post.group %}
          <li class="nav-item"> 
            <a class="nav-link" href="{% url 'posts:group_posts' post.group.slug %}">
              <button type="submit" class="btn btn-light"> все записи группы </button>
            </a>
          </li>
        {% endif %}
          <li class="nav-item"> 
            <a class="nav-link" href={% url 'posts:post_detail' post.id %}>
              <button type="submit" class="btn btn-light"> подробная информация </button>
            </a>
          </li>
        </ul>
      {% if not forloop.last %}<hr>{% endif %}
    </article>
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}